import XCTest

final class DashboardRedesignSourceTests: XCTestCase {
    func testDashboardIsTabbedNotOneScrollingPage() throws {
        let dashboard = try source("Sources/App/Dashboard/DashboardView.swift")
        XCTAssertFalse(dashboard.contains("accountGrid"))
        XCTAssertTrue(dashboard.contains("DashboardProfileColumnView"))
        XCTAssertTrue(dashboard.contains("dashboardVisible"))
        XCTAssertTrue(dashboard.contains("refreshOnDashboardOpen()"))
        XCTAssertTrue(dashboard.contains("noteDashboardClosed()"))
        XCTAssertTrue(dashboard.contains("onDisappear"))
        XCTAssertFalse(dashboard.contains("DashboardPrototypeSwitcher"))
    }

    func testAccountsTableAndModelTableExist() throws {
        let accounts = try source("Sources/App/Dashboard/DashboardAccountsPane.swift")
        let table = try source("Sources/App/Dashboard/DashboardAccountTable.swift")
        let models = try source("Sources/App/Dashboard/UsageModelCatalogView.swift")
        XCTAssertTrue(accounts.contains("DashboardAccountLayout"))
        XCTAssertTrue(accounts.contains("layout.symbolName"))
        XCTAssertFalse(accounts.contains("Text(layout.title)"))
        let layout = try source("Sources/Domain/DashboardAccountSort.swift")
        XCTAssertTrue(layout.contains("tablecells"))
        XCTAssertTrue(layout.contains("list.bullet"))
        XCTAssertTrue(accounts.contains("DashboardConnectAccountRow"))
        XCTAssertTrue(accounts.contains("layoutSwitcher"))
        XCTAssertFalse(accounts.contains("pickerStyle(.segmented)"))
        XCTAssertFalse(accounts.contains("roundedBorder"))
        XCTAssertTrue(accounts.contains("DashboardPillSegmentedControl"))
        XCTAssertTrue(accounts.contains("Filter accounts"))
        XCTAssertTrue(accounts.contains("focusEffectDisabled"))
        XCTAssertTrue(accounts.contains("DashboardAccountTable"))
        XCTAssertFalse(accounts.contains("SeatCardView"))
        XCTAssertFalse(accounts.contains("countCopy"))
        XCTAssertTrue(table.contains("accountSort"))
        XCTAssertTrue(table.contains("ActiveMenuMarker"))
        XCTAssertTrue(table.contains("revealedEmail"))
        XCTAssertTrue(table.contains("CursorProfileAvatar"))
        XCTAssertTrue(table.contains("accountFilter"))
        XCTAssertTrue(table.contains("accountUsageMetric"))
        let avatar = try source("Sources/App/Design/CursorProfile.swift")
        XCTAssertTrue(avatar.contains("ProfilePictureImage"))
        XCTAssertTrue(avatar.contains("clipShape(Circle())"))
        XCTAssertTrue(avatar.contains("ProfileInitial.letter"))
        XCTAssertFalse(avatar.contains("prefix(2)"))
        let loader = try source("Sources/App/Design/ProfilePictureImage.swift")
        XCTAssertTrue(loader.contains("User-Agent"))
        XCTAssertTrue(loader.contains("fm"))
        XCTAssertTrue(loader.contains("jpg"))
        XCTAssertTrue(loader.contains("signed"))
        XCTAssertFalse(loader.contains("image/avif"))
        XCTAssertTrue(loader.contains("prefetch"))
        let metric = try source("Sources/Domain/AccountUsageMetric.swift")
        XCTAssertTrue(metric.contains("tokens"))
        XCTAssertFalse(metric.contains("case onDemand"))
        XCTAssertFalse(metric.contains("case .onDemand"))
        XCTAssertFalse(table.contains("headerDivider"))
        XCTAssertFalse(table.contains("sortHeader(\"Active\""))
        XCTAssertFalse(table.contains("Color.accentColor"))
        XCTAssertTrue(table.contains(".reset"))
        XCTAssertTrue(table.contains("\"API\"") || table.contains("case .percent: \"API\""))
        XCTAssertTrue(table.contains("On-demand"))
        XCTAssertTrue(table.contains("presentOnDemandEditor"))
        let dashboard = try source("Sources/App/Dashboard/DashboardView.swift")
        XCTAssertTrue(dashboard.contains("OnDemandEditSheet"))
        XCTAssertTrue(dashboard.contains("onDemandEditorSeatID"))
        let meter = try source("Sources/App/Dashboard/DashboardSortHeader.swift")
        XCTAssertTrue(meter.contains("HStack(spacing: 6)"))
        XCTAssertFalse(meter.contains("chartAccent"))
        XCTAssertTrue(models.contains("DashboardModelOrdering"))
        XCTAssertTrue(models.contains("DashboardSortHeader"))
    }

    func testUsageAndModelsAreSeparateSurfaces() throws {
        let usage = try source("Sources/App/Dashboard/DashboardUsagePane.swift")
        let models = try source("Sources/App/Dashboard/DashboardModelsPane.swift")
        let insights = try source("Sources/App/Dashboard/UsageInsightsView.swift")
        XCTAssertTrue(usage.contains("includeModels: false"))
        XCTAssertTrue(usage.contains("UsageChartView"))
        XCTAssertTrue(usage.contains("UsageActivityHeatmapView"))
        let chartRange = try XCTUnwrap(usage.range(of: "UsageChartView"))
        let heatRange = try XCTUnwrap(usage.range(of: "UsageActivityHeatmapView"))
        XCTAssertLessThan(chartRange.lowerBound, heatRange.lowerBound)
        let heatmap = try source("Sources/App/Dashboard/UsageActivityHeatmapView.swift")
        XCTAssertTrue(heatmap.contains("1.08"))
        XCTAssertTrue(heatmap.contains("CursorProfileHoverCard"))
        XCTAssertTrue(heatmap.contains("rounded-full") || heatmap.contains("Circle()"))
        XCTAssertTrue(usage.contains("UsageInsightsChartsView"))
        let stats = try source("Sources/App/Dashboard/DashboardUsageStatsRow.swift")
        XCTAssertTrue(stats.contains("Tokens · this account"))
        XCTAssertTrue(stats.contains("Tokens · all accounts"))
        XCTAssertTrue(stats.contains("tokenHeadline"))
        XCTAssertTrue(usage.contains("includeCharts: false"))
        XCTAssertFalse(usage.contains("UsageModelCatalogView"))
        XCTAssertTrue(models.contains("UsageModelCatalogView"))
        XCTAssertTrue(models.contains("DashboardGroupBySelect"))
        XCTAssertTrue(models.contains("Group by"))
        XCTAssertTrue(models.contains("triggerLabel"))
        XCTAssertFalse(models.contains("Group by family"))
        XCTAssertFalse(models.contains("toggleStyle(.checkbox)"))
        let group = try source("Sources/Domain/DashboardModelSort.swift")
        XCTAssertTrue(group.contains("enum DashboardModelGroup"))
        XCTAssertTrue(group.contains("No grouping"))
        XCTAssertTrue(group.contains("By family"))
        XCTAssertFalse(models.contains("UsageChartView"))
        XCTAssertTrue(insights.contains("includeModels"))
        XCTAssertTrue(insights.contains("includeCharts"))
        let charts = try source("Sources/App/Dashboard/UsageInsightsChartsView.swift")
        XCTAssertFalse(charts.contains("UsageActivityHeatmapView"))
        let chart = try source("Sources/App/Dashboard/UsageChartView.swift")
        XCTAssertTrue(chart.contains("Tokens · all accounts"))
        XCTAssertTrue(chart.contains("Tokens · this account"))
        let plot = try source("Sources/App/Dashboard/UsageChartPlotView.swift")
        XCTAssertTrue(plot.contains("chartAccent"))
        XCTAssertTrue(plot.contains("opacity(0.06)"))
        let fonts = try source("Sources/App/Design/CursorProfile.swift")
        XCTAssertTrue(fonts.contains("CursorProfileHoverCard"))
        XCTAssertTrue(fonts.contains("mixAccent"))
    }

    func testProductionShipsProfileColumn() throws {
        let dashboard = try source("Sources/App/Dashboard/DashboardView.swift")
        XCTAssertTrue(dashboard.contains("DashboardProfileColumnView(model: model, dashboardVisible: model.dashboardVisible)"))
        XCTAssertFalse(dashboard.contains("DashboardSettingsRailView"))
        XCTAssertFalse(dashboard.contains("DashboardInspectorView"))
    }

    func testDashboardUsesPageHeaderNotToolbarPills() throws {
        let dashboard = try source("Sources/App/Dashboard/DashboardView.swift")
        let chrome = try source("Sources/App/Design/LiquidGlass.swift")
        let app = try source("Sources/App/CursorBarApp.swift")
        let column = try source("Sources/App/Dashboard/DashboardProfileColumnView.swift")
        XCTAssertFalse(dashboard.contains(".toolbar"))
        XCTAssertFalse(dashboard.contains("sharedBackgroundVisibility"))
        XCTAssertFalse(dashboard.contains("DashboardToolbarStatus"))
        XCTAssertTrue(dashboard.contains("windowTitle"))
        XCTAssertFalse(dashboard.contains("DashboardGlassTitleBar("))
        XCTAssertFalse(dashboard.contains("dashboardHidesWindowTitle"))
        XCTAssertTrue(chrome.contains("titleVisibility = .hidden"))
        XCTAssertFalse(chrome.contains("window.title = \"MultiCursor\""))
        XCTAssertFalse(chrome.contains("window.title = \"Cursor Accounts\""))
        XCTAssertTrue(chrome.contains("titlebarSeparatorStyle = .none"))
        XCTAssertTrue(chrome.contains("titlebarAppearsTransparent = true"))
        XCTAssertTrue(chrome.contains("styleMask.remove(.fullSizeContentView)"))
        XCTAssertFalse(chrome.contains("styleMask.insert(.fullSizeContentView)"))
        XCTAssertTrue(chrome.contains("window.toolbar = nil"))
        XCTAssertTrue(chrome.contains("isOpaque = true"))
        XCTAssertFalse(chrome.contains("isOpaque = false"))
        XCTAssertFalse(chrome.contains("backgroundColor = .clear"))
        XCTAssertFalse(chrome.contains("clearHostingFill"))
        XCTAssertFalse(chrome.contains("underWindowBackground"))
        XCTAssertFalse(chrome.contains("behindWindow"))
        XCTAssertFalse(chrome.contains("BehindWindowMaterial"))
        XCTAssertFalse(chrome.contains("dashboardWindowMaterial"))
        XCTAssertFalse(chrome.contains("containerBackground"))
        XCTAssertTrue(chrome.contains("titleFill"))
        XCTAssertFalse(chrome.contains("cursorbar.titlebar-fill"))
        XCTAssertFalse(chrome.contains("installTitlebarColorFill"))
        XCTAssertTrue(chrome.contains("ignoresMouseEvents = false"))
        XCTAssertTrue(chrome.contains("paintTitlebarToMatchPage"))
        XCTAssertTrue(chrome.contains("hostsTrafficLights"))
        XCTAssertTrue(chrome.contains("intersectsTrafficLights"))
        XCTAssertTrue(chrome.contains("ThemeWidgetView"))
        XCTAssertTrue(chrome.contains("separator"))
        XCTAssertTrue(chrome.contains("trafficLightGutter"))
        XCTAssertFalse(chrome.contains("syncBackground"))
        XCTAssertFalse(chrome.contains("NSToolbar(identifier"))
        XCTAssertFalse(app.contains("hiddenTitleBar"))
        XCTAssertFalse(app.contains("windowToolbarStyle(.unified)"))
        XCTAssertTrue(app.contains("MenuBarStatusLabel"))
        XCTAssertTrue(app.contains("model.menuBarUsage"))
        let extra = try source("Sources/App/Menu/MenuBarStatusLabel.swift")
        XCTAssertTrue(extra.contains("visibleTitle"))
        XCTAssertTrue(extra.contains("showsNumbers"))
        let seatMenu = try source("Sources/App/Menu/SeatMenuContent.swift")
        XCTAssertTrue(seatMenu.contains("Show in Dashboard"))
        XCTAssertFalse(seatMenu.contains("Show in header"))
        let menu = try source("Sources/App/MenuBarRoot.swift")
        XCTAssertTrue(menu.contains("model.updates.menuTitle"))
        XCTAssertTrue(column.contains("DashboardPageHeader"))
        XCTAssertTrue(column.contains("DashboardTabBody"))
        XCTAssertTrue(column.contains("dashboardScrollEdge"))
        XCTAssertTrue(column.contains(".padding(.top, 36)"))
        XCTAssertTrue(column.contains(".padding(.bottom, 16)"))
        XCTAssertTrue(column.contains("scrollContentBackground(.hidden)"))
        XCTAssertTrue(column.contains("CursorProfile.page"))
        XCTAssertFalse(column.contains("BehindWindowMaterial"))
        XCTAssertFalse(column.contains(".regularMaterial"))
        XCTAssertFalse(dashboard.contains("dashboardWindowMaterial()"))
        XCTAssertFalse(dashboard.contains("BehindWindowMaterial"))
        XCTAssertFalse(column.contains("chromeLeading"))
        XCTAssertFalse(column.contains("ignoresSafeArea"))
        XCTAssertFalse(column.contains("offset(y: -1)"))
        XCTAssertTrue(chrome.contains("trafficLightsLeading: CGFloat = 80"))
        let presenter = try source("Sources/App/Dashboard/DashboardWindowPresenter.swift")
        let delegate = try source("Sources/App/AppDelegate.swift")
        XCTAssertTrue(presenter.contains("setActivationPolicy(.regular)"))
        XCTAssertTrue(presenter.contains("setActivationPolicy(.accessory)"))
        XCTAssertTrue(presenter.contains("applyNormalWindowStacking"))
        XCTAssertTrue(presenter.contains("level = .normal"))
        XCTAssertFalse(presenter.contains("level = .floating"))
        XCTAssertFalse(presenter.contains("orderFrontRegardless"))
        XCTAssertFalse(presenter.contains("moveToActiveSpace"))
        XCTAssertTrue(delegate.contains("applicationShouldHandleReopen"))
        let fonts = try source("Sources/App/Design/CursorProfile.swift")
        XCTAssertTrue(fonts.contains("static let table"))
        XCTAssertTrue(fonts.contains("design: .default"))
        let titleBar = try source("Sources/App/Dashboard/DashboardGlassTitleBar.swift")
        XCTAssertFalse(titleBar.contains("pickerStyle(.segmented)"))
        XCTAssertTrue(titleBar.contains("DashboardProfileTabBar"))
        XCTAssertTrue(titleBar.contains("DashboardPillSegmentedControl"))
        XCTAssertTrue(titleBar.contains("DashboardPageHeader"))
        XCTAssertFalse(titleBar.contains("Add Account"))
        XCTAssertFalse(titleBar.contains("connectAnotherAccount"))
        let accounts = try source("Sources/App/Dashboard/DashboardAccountsPane.swift")
        XCTAssertTrue(accounts.contains("Add Account"))
        XCTAssertTrue(accounts.contains("layoutSwitcher"))
        let verify = try source("Sources/App/VerifyDashboardPresenter.swift")
        XCTAssertTrue(verify.contains("--account-layout="))
        XCTAssertTrue(verify.contains("accountLayout = .detail"))
        XCTAssertTrue(accounts.contains("addAccountButton"))
        XCTAssertTrue(accounts.contains("maxWidth: .infinity"))
        XCTAssertTrue(accounts.contains("in: Capsule(style: .continuous)"))
        XCTAssertTrue(accounts.contains("fixedSize(horizontal: true, vertical: false)"))
        XCTAssertTrue(accounts.contains("layoutPriority(1)"))
        XCTAssertFalse(accounts.contains("Spacer(minLength: 0)"))
        XCTAssertFalse(accounts.contains("maxWidth: 200"))
        let switcherRange = try XCTUnwrap(accounts.range(of: "layoutSwitcher"))
        let addRange = try XCTUnwrap(accounts.range(of: "addAccountButton"))
        XCTAssertLessThan(switcherRange.lowerBound, addRange.lowerBound)
        let models = try source("Sources/App/Dashboard/DashboardModelsPane.swift")
        let usage = try source("Sources/App/Dashboard/DashboardUsagePane.swift")
        XCTAssertFalse(models.contains("Add Account"))
        XCTAssertFalse(usage.contains("Add Account"))
        XCTAssertTrue(titleBar.contains("ActiveMenuMarker"))
        XCTAssertTrue(titleBar.contains("CursorProfileAvatar"))
        XCTAssertTrue(titleBar.contains("dashboardTitle"))
        XCTAssertTrue(titleBar.contains("isDesktopBound"))
        XCTAssertTrue(titleBar.contains("revealedEmail"))
        XCTAssertTrue(titleBar.contains("DashboardTeaserStat"))
        XCTAssertTrue(titleBar.contains("\"API\""))
        XCTAssertTrue(titleBar.contains("presentOnDemandEditor"))
        XCTAssertTrue(titleBar.contains("Capsule(style: .continuous)"))
    }

    private func source(_ relative: String) throws -> String {
        let root = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        return try String(contentsOf: root.appendingPathComponent(relative))
    }
}
